# Generated by Django 4.2.6 on 2025-02-02 09:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqProjrctApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQEXAMPLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Answer')),
                ('question_hi', models.TextField(blank=True, null=True, verbose_name='Question in Hindi')),
                ('question_bn', models.TextField(blank=True, null=True, verbose_name='Question in Bengali')),
            ],
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
